"""initial migration

Revision ID: 2df5c74f82e
Revises: None
Create Date: 2016-12-08 13:34:56.678776

"""

# revision identifiers, used by Alembic.
revision = '2df5c74f82e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bed',
    sa.Column('file_location', sa.Text(length=64), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=32), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('md5'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('file_location'),
    sa.UniqueConstraint('label')
    )
    op.create_table('identity',
    sa.Column('organism', sa.String(length=32), nullable=True),
    sa.Column('technique', sa.String(length=32), nullable=True),
    sa.Column('afactor', sa.String(length=32), nullable=True),
    sa.Column('tissue', sa.String(length=32), nullable=True),
    sa.Column('cline', sa.String(length=32), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['md5'], ['bed.md5'], ),
    sa.PrimaryKeyConstraint('md5')
    )
    op.create_table('colocalization',
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('md5_1', sa.String(length=32), nullable=False),
    sa.Column('md5_2', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['md5_1'], ['bed.md5'], ),
    sa.ForeignKeyConstraint(['md5_2'], ['bed.md5'], ),
    sa.PrimaryKeyConstraint('method', 'md5_1', 'md5_2')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colocalization')
    op.drop_table('identity')
    op.drop_table('bed')
    ### end Alembic commands ###
