"""initial migration

Revision ID: 52d4a4bf1896
Revises: None
Create Date: 2016-09-21 14:04:43.818054

"""

# revision identifiers, used by Alembic.
revision = '52d4a4bf1896'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_bed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('file_location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_location'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jaccard',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('file_location', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['p_id'], ['public_bed.id'], ),
    sa.PrimaryKeyConstraint('p_id'),
    sa.UniqueConstraint('file_location')
    )
    op.create_index(op.f('ix_jaccard_name'), 'jaccard', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jaccard_name'), table_name='jaccard')
    op.drop_table('jaccard')
    op.drop_table('public_bed')
    ### end Alembic commands ###
