"""initial migrate

Revision ID: 784e55fc8133
Revises: None
Create Date: 2016-09-23 11:50:46.336269

"""

# revision identifiers, used by Alembic.
revision = '784e55fc8133'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_bed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('file_location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_location'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jaccard',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('u_inter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['p_id'], ['public_bed.id'], ),
    sa.PrimaryKeyConstraint('p_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jaccard')
    op.drop_table('public_bed')
    ### end Alembic commands ###
